<?php

/**
 * @file
 * Contains site_apikey.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
 
function site_apikey_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_apikey module.
    case 'help.page.site_apikey':
      return '<p>' . t('A module to set API Key for the site.') . '</p>';
  }
}

/**
* Implements hook_form_FORM-ID_alter
* This is to Add New field in Site information page
*/
function site_apikey_form_system_site_information_settings_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
    $site_apikey_setting	= \Drupal::config('system.site')->get('siteapikey')?\Drupal::config('system.site')->get('siteapikey'):t('No API Key yet');
    if(in_array("administrator", \Drupal::currentUser()->getRoles())) {
            $form['site_information']['siteapikey'] = [
                '#type' => 'textfield',
                '#title' => t('Site API Key'),
                '#default_value' => $site_apikey_setting,
                '#weight' => '2',
			    '#placeholder' => t('No API Key yet'),
            ];	
		    $form['actions']['submit']['#value'] = t('Update Configuration');
            // extra submit form handle
            $form['#submit'][] = 'Drupal\site_apikey\Controller\SiteApikeyController::site_apikey_form_submit';			
    }	
}