version: '3'
networks:
  tickcomm_internal:
    driver: bridge
services:
  influxdb:
    image: influxdb:1.8
    volumes:
      - ./influxdb/data:/var/lib/influxdb
      - ./influxdb/config/:/etc/influxdb/
    ports:
      - "8086:8086"
      - "8082:8082"
      - "8089:8089"
    networks:
      - tickcomm_internal
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/:/etc/telegraf/
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/rootfs/sys
      - /proc:/rootfs/proc
      - /etc:/rootfs/etc
    ports:
      - "8092:8092/udp"
      - 8094:8094
      - "8125:8125/udp"
    environment:
      HOST_PROC: /rootfs/proc
      HOST_SYS:  /root/sys
      HOST_ETC:  /root/etc
    depends_on:
      - influxdb
    networks:
      - tickcomm_internal

  kapacitor:
    image: kapacitor:latest
    volumes:
      - ./kapacitor/data/:/var/lib/kapacitor
      - ./kapacitor/config/:/etc/kapacitor/
    ports:
      - "9092:9092"
    networks:
      - tickcomm_internal

  chronograf:
    image: chronograf:latest
    volumes:
      - ./chronograf/data/:/var/lib/chronograf/
    ports:
      - "8888:8888"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
    depends_on:
      - kapacitor
      - influxdb
      - telegraf
    networks:
      - tickcomm_internal
